### ISSUE TITLE
plugin.pilot.traefik.io : no such host

### ISSUE THREAD

**Issue by lazyest** [traefik/plugin-rewritebody#24] opened 2022-03-16 11:24 UTC
I know that its moslty not here but what workaround can be found?
today it started appearing this kind of crap:
traefik.go:76: command traefik error: failed to download plugin github.com/traefik/plugin-rewritebody: failed to call service: Get "https://plugin.pilot.traefik.io/public/download/github.com/traefik/plugin-rewritebody/v0.3.1": dial tcp: lookup plugin.pilot.traefik.io on 127.0.0.11:53: no such host

**Comment by ldez** [comment] 2022-03-16 11:36
Hello,

Thank you for your report, the problem is fixed now.

**Closed by ldez** 2022-03-16 11:36 UTC
Labels: kind/bug/confirmed
